fname = input("Enter First Name: ")
lname = input("Enter Last Name: ")
mname = input("Enter Middle Name: ")
bday = input("Enter Birthday: ")
gender = input("Enter Gender: ")
address = input("Enter Address: ")
course = input("Enter Course: ")
yr_lvl = input("Enter Year Level: ")

print("================================")
print("Name:", fname, mname, lname)
print("Birthday:", bday)
print("Gender:", gender)
print("Address:", address)
print("Course:", course)
print("Year Level:", yr_lvl)

